# Generated by Django 4.1.4 on 2024-06-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='back_urls_failure',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='back_urls_pending',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='back_urls_success',
        ),
        migrations.AddField(
            model_name='preference',
            name='back_urls',
            field=models.JSONField(default='2024-06-11T09:22:30.123456'),
            preserve_default=False,
        ),
    ]
