# Generated by Django 4.1.4 on 2024-06-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_preference_back_urls_failure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='back_urls',
        ),
        migrations.AddField(
            model_name='preference',
            name='back_url_failure',
            field=models.URLField(default='2024-06-11T09:22:30.123456'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preference',
            name='back_url_pending',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preference',
            name='back_url_success',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
